/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

/**
 *
 * @author DIEGO
 */
public class CrearTurno extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearTurno
     */
    public CrearTurno() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        panGeneracionTurno5 = new javax.swing.JPanel();
        lblPan5Titulo = new javax.swing.JLabel();
        lblPan5pregunta = new javax.swing.JLabel();
        pnaPan5ContenedorTicket = new javax.swing.JPanel();
        lblPan5TituloTurno = new javax.swing.JLabel();
        sepa1 = new javax.swing.JSeparator();
        lblPan5Codigo = new javax.swing.JLabel();
        sepa2 = new javax.swing.JSeparator();
        lblFecha = new javax.swing.JLabel();
        lblPan5TituloNombre = new javax.swing.JLabel();
        lblTituloServicio = new javax.swing.JLabel();
        panDiscapacidad4 = new javax.swing.JPanel();
        lblPan4pregunta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panEscogerServicio3 = new javax.swing.JPanel();
        lblPan3pregunta = new javax.swing.JLabel();
        lblPan3bienvenida = new javax.swing.JLabel();
        btnPan3PagoServicios = new javax.swing.JButton();
        btnPan3NuevoProducto = new javax.swing.JButton();
        btnPan3RetiroDeposito = new javax.swing.JButton();
        btnPan3Asesoria = new javax.swing.JButton();
        panIngresarDoc2 = new javax.swing.JPanel();
        lblPan2pregunta = new javax.swing.JLabel();
        btnPan2Teclado5 = new javax.swing.JButton();
        btnPan2Teclado6 = new javax.swing.JButton();
        btnPan2Teclado4 = new javax.swing.JButton();
        btnPan2Teclado1 = new javax.swing.JButton();
        btnPan2Teclado2 = new javax.swing.JButton();
        btnPan2Teclado3 = new javax.swing.JButton();
        btnPan2Teclado0 = new javax.swing.JButton();
        decoracionPan2TecladoDe = new javax.swing.JPanel();
        decoracionPan2TecladoIz = new javax.swing.JPanel();
        btnPan2Teclado7 = new javax.swing.JButton();
        btnPan2Teclado8 = new javax.swing.JButton();
        btnPan2Teclado9 = new javax.swing.JButton();
        txtPan2Documento = new javax.swing.JTextField();
        btnPan2Continuar = new javax.swing.JButton();
        panEscogerCliente1 = new javax.swing.JPanel();
        lblPan1pregunta = new javax.swing.JLabel();
        btnPan1Si = new javax.swing.JButton();
        btnPan1No = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPasswordField1.setText("jPasswordField1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPan5Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan5Titulo.setText("Turno generado");

        lblPan5pregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan5pregunta.setText("¡Gracias, por confiar en nosotros!");

        pnaPan5ContenedorTicket.setBackground(new java.awt.Color(255, 255, 255));

        lblPan5TituloTurno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPan5TituloTurno.setText("Tu turno:");

        sepa1.setBackground(new java.awt.Color(0, 0, 0));
        sepa1.setForeground(new java.awt.Color(0, 0, 0));

        lblPan5Codigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPan5Codigo.setText("*******");

        sepa2.setBackground(new java.awt.Color(0, 0, 0));
        sepa2.setForeground(new java.awt.Color(0, 0, 0));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setText("*******");

        lblPan5TituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPan5TituloNombre.setText("Espere a ser llamado");

        lblTituloServicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloServicio.setText("Sin el ticket no puede ser atendido");

        javax.swing.GroupLayout pnaPan5ContenedorTicketLayout = new javax.swing.GroupLayout(pnaPan5ContenedorTicket);
        pnaPan5ContenedorTicket.setLayout(pnaPan5ContenedorTicketLayout);
        pnaPan5ContenedorTicketLayout.setHorizontalGroup(
            pnaPan5ContenedorTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepa1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sepa2)
            .addGroup(pnaPan5ContenedorTicketLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblPan5TituloNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnaPan5ContenedorTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addComponent(lblPan5Codigo)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addComponent(lblPan5TituloTurno)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addComponent(lblTituloServicio)
                        .addGap(17, 17, 17))))
        );
        pnaPan5ContenedorTicketLayout.setVerticalGroup(
            pnaPan5ContenedorTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaPan5ContenedorTicketLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPan5TituloTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepa1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPan5Codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepa2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPan5TituloNombre)
                .addGap(18, 18, 18)
                .addComponent(lblTituloServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblFecha)
                .addContainerGap())
        );

        javax.swing.GroupLayout panGeneracionTurno5Layout = new javax.swing.GroupLayout(panGeneracionTurno5);
        panGeneracionTurno5.setLayout(panGeneracionTurno5Layout);
        panGeneracionTurno5Layout.setHorizontalGroup(
            panGeneracionTurno5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneracionTurno5Layout.createSequentialGroup()
                .addGroup(panGeneracionTurno5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGeneracionTurno5Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(lblPan5pregunta))
                    .addGroup(panGeneracionTurno5Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(lblPan5Titulo))
                    .addGroup(panGeneracionTurno5Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(pnaPan5ContenedorTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        panGeneracionTurno5Layout.setVerticalGroup(
            panGeneracionTurno5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneracionTurno5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblPan5Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPan5pregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnaPan5ContenedorTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(panGeneracionTurno5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 380));

        lblPan4pregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan4pregunta.setText("¿Cumple alguna condición para atención preferencial?");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Adulto mayor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Persona con discapacidad");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Embarazada");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDiscapacidad4Layout = new javax.swing.GroupLayout(panDiscapacidad4);
        panDiscapacidad4.setLayout(panDiscapacidad4Layout);
        panDiscapacidad4Layout.setHorizontalGroup(
            panDiscapacidad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDiscapacidad4Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDiscapacidad4Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(lblPan4pregunta)
                .addGap(185, 185, 185))
            .addGroup(panDiscapacidad4Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDiscapacidad4Layout.setVerticalGroup(
            panDiscapacidad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDiscapacidad4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPan4pregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(panDiscapacidad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(panDiscapacidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 370));

        lblPan3pregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan3pregunta.setText("¿Que servicio desea realizar?");

        lblPan3bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan3bienvenida.setText("Bienvenido ");

        btnPan3PagoServicios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan3PagoServicios.setText("Pago de servicios");
        btnPan3PagoServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan3PagoServiciosActionPerformed(evt);
            }
        });

        btnPan3NuevoProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan3NuevoProducto.setText("Nuevo producto");

        btnPan3RetiroDeposito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan3RetiroDeposito.setText("Retiro o deposito");

        btnPan3Asesoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan3Asesoria.setText("Asesoria ");
        btnPan3Asesoria.setToolTipText("");

        javax.swing.GroupLayout panEscogerServicio3Layout = new javax.swing.GroupLayout(panEscogerServicio3);
        panEscogerServicio3.setLayout(panEscogerServicio3Layout);
        panEscogerServicio3Layout.setHorizontalGroup(
            panEscogerServicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEscogerServicio3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(panEscogerServicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPan3Asesoria, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPan3PagoServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panEscogerServicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPan3NuevoProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPan3RetiroDeposito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEscogerServicio3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panEscogerServicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEscogerServicio3Layout.createSequentialGroup()
                        .addComponent(lblPan3bienvenida)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEscogerServicio3Layout.createSequentialGroup()
                        .addComponent(lblPan3pregunta)
                        .addGap(274, 274, 274))))
        );
        panEscogerServicio3Layout.setVerticalGroup(
            panEscogerServicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscogerServicio3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblPan3bienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPan3pregunta)
                .addGap(48, 48, 48)
                .addGroup(panEscogerServicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPan3PagoServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPan3NuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panEscogerServicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPan3RetiroDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPan3Asesoria, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(panEscogerServicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 370));

        lblPan2pregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan2pregunta.setText("Por favor, ingresa tu número de documento para continuar con la solicitud.");

        btnPan2Teclado5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado5.setText("5");
        btnPan2Teclado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan2Teclado5ActionPerformed(evt);
            }
        });

        btnPan2Teclado6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado6.setText("6");

        btnPan2Teclado4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado4.setText("4");
        btnPan2Teclado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan2Teclado4ActionPerformed(evt);
            }
        });

        btnPan2Teclado1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado1.setText("1");

        btnPan2Teclado2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado2.setText("2");
        btnPan2Teclado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan2Teclado2ActionPerformed(evt);
            }
        });

        btnPan2Teclado3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado3.setText("3");
        btnPan2Teclado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan2Teclado3ActionPerformed(evt);
            }
        });

        btnPan2Teclado0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado0.setText("0");

        decoracionPan2TecladoDe.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout decoracionPan2TecladoDeLayout = new javax.swing.GroupLayout(decoracionPan2TecladoDe);
        decoracionPan2TecladoDe.setLayout(decoracionPan2TecladoDeLayout);
        decoracionPan2TecladoDeLayout.setHorizontalGroup(
            decoracionPan2TecladoDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        decoracionPan2TecladoDeLayout.setVerticalGroup(
            decoracionPan2TecladoDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        decoracionPan2TecladoIz.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout decoracionPan2TecladoIzLayout = new javax.swing.GroupLayout(decoracionPan2TecladoIz);
        decoracionPan2TecladoIz.setLayout(decoracionPan2TecladoIzLayout);
        decoracionPan2TecladoIzLayout.setHorizontalGroup(
            decoracionPan2TecladoIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        decoracionPan2TecladoIzLayout.setVerticalGroup(
            decoracionPan2TecladoIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        btnPan2Teclado7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado7.setText("7");

        btnPan2Teclado8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado8.setText("8");
        btnPan2Teclado8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan2Teclado8ActionPerformed(evt);
            }
        });

        btnPan2Teclado9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Teclado9.setText("9");
        btnPan2Teclado9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan2Teclado9ActionPerformed(evt);
            }
        });

        txtPan2Documento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPan2Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPan2DocumentoActionPerformed(evt);
            }
        });

        btnPan2Continuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan2Continuar.setText("Continuar");

        javax.swing.GroupLayout panIngresarDoc2Layout = new javax.swing.GroupLayout(panIngresarDoc2);
        panIngresarDoc2.setLayout(panIngresarDoc2Layout);
        panIngresarDoc2Layout.setHorizontalGroup(
            panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                        .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPan2Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnPan2Continuar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panIngresarDoc2Layout.createSequentialGroup()
                                .addComponent(decoracionPan2TecladoIz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnPan2Teclado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPan2Teclado0, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPan2Teclado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(decoracionPan2TecladoDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panIngresarDoc2Layout.createSequentialGroup()
                                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPan2Teclado9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPan2Teclado6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPan2Teclado3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPan2Teclado5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPan2Teclado8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPan2Teclado4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(btnPan2Teclado7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(82, 82, 82))
                    .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                        .addComponent(lblPan2pregunta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panIngresarDoc2Layout.setVerticalGroup(
            panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPan2pregunta)
                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPan2Teclado8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPan2Teclado7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPan2Teclado9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPan2Teclado5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPan2Teclado4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPan2Teclado6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPan2Teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPan2Teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPan2Teclado3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panIngresarDoc2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtPan2Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(panIngresarDoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPan2Teclado0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(decoracionPan2TecladoDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(decoracionPan2TecladoIz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panIngresarDoc2Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnPan2Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(panIngresarDoc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 820, 370));

        lblPan1pregunta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPan1pregunta.setText("¿Ya eres cliente del BBVA?");

        btnPan1Si.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan1Si.setText("Sí, soy cliente BBVA");

        btnPan1No.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan1No.setText("No, aún no soy cliente");

        javax.swing.GroupLayout panEscogerCliente1Layout = new javax.swing.GroupLayout(panEscogerCliente1);
        panEscogerCliente1.setLayout(panEscogerCliente1Layout);
        panEscogerCliente1Layout.setHorizontalGroup(
            panEscogerCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscogerCliente1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPan1pregunta)
                .addGap(260, 260, 260))
            .addGroup(panEscogerCliente1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnPan1Si, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btnPan1No, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panEscogerCliente1Layout.setVerticalGroup(
            panEscogerCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscogerCliente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPan1pregunta)
                .addGap(108, 108, 108)
                .addGroup(panEscogerCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPan1Si, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPan1No, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        getContentPane().add(panEscogerCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 370));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Generar turno");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPan2Teclado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan2Teclado5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPan2Teclado5ActionPerformed

    private void btnPan2Teclado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan2Teclado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPan2Teclado2ActionPerformed

    private void btnPan2Teclado8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan2Teclado8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPan2Teclado8ActionPerformed

    private void btnPan2Teclado9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan2Teclado9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPan2Teclado9ActionPerformed

    private void btnPan2Teclado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan2Teclado4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPan2Teclado4ActionPerformed

    private void btnPan2Teclado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan2Teclado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPan2Teclado3ActionPerformed

    private void txtPan2DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPan2DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPan2DocumentoActionPerformed

    private void btnPan3PagoServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan3PagoServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPan3PagoServiciosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPan1No;
    private javax.swing.JButton btnPan1Si;
    private javax.swing.JButton btnPan2Continuar;
    private javax.swing.JButton btnPan2Teclado0;
    private javax.swing.JButton btnPan2Teclado1;
    private javax.swing.JButton btnPan2Teclado2;
    private javax.swing.JButton btnPan2Teclado3;
    private javax.swing.JButton btnPan2Teclado4;
    private javax.swing.JButton btnPan2Teclado5;
    private javax.swing.JButton btnPan2Teclado6;
    private javax.swing.JButton btnPan2Teclado7;
    private javax.swing.JButton btnPan2Teclado8;
    private javax.swing.JButton btnPan2Teclado9;
    private javax.swing.JButton btnPan3Asesoria;
    private javax.swing.JButton btnPan3NuevoProducto;
    private javax.swing.JButton btnPan3PagoServicios;
    private javax.swing.JButton btnPan3RetiroDeposito;
    private javax.swing.JPanel decoracionPan2TecladoDe;
    private javax.swing.JPanel decoracionPan2TecladoIz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPan1pregunta;
    private javax.swing.JLabel lblPan2pregunta;
    private javax.swing.JLabel lblPan3bienvenida;
    private javax.swing.JLabel lblPan3pregunta;
    private javax.swing.JLabel lblPan4pregunta;
    private javax.swing.JLabel lblPan5Codigo;
    private javax.swing.JLabel lblPan5Titulo;
    private javax.swing.JLabel lblPan5TituloNombre;
    private javax.swing.JLabel lblPan5TituloTurno;
    private javax.swing.JLabel lblPan5pregunta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloServicio;
    private javax.swing.JPanel panDiscapacidad4;
    private javax.swing.JPanel panEscogerCliente1;
    private javax.swing.JPanel panEscogerServicio3;
    private javax.swing.JPanel panGeneracionTurno5;
    private javax.swing.JPanel panIngresarDoc2;
    private javax.swing.JPanel pnaPan5ContenedorTicket;
    private javax.swing.JSeparator sepa1;
    private javax.swing.JSeparator sepa2;
    private javax.swing.JTextField txtPan2Documento;
    // End of variables declaration//GEN-END:variables
}
