/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.entity.TriagePrioridad;

/**
 *
 * @author DIEGO
 */
public class CuartoPasoCrearTurno extends javax.swing.JInternalFrame {

   private CrearTurno principal;
   
    public CuartoPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmbarazada = new javax.swing.JButton();
        btnMayor = new javax.swing.JButton();
        btnDiscapacidad = new javax.swing.JButton();
        btnNO = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblpregunta = new javax.swing.JLabel();

        btnEmbarazada.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnEmbarazada.setText("Embarazada");
        btnEmbarazada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmbarazadaActionPerformed(evt);
            }
        });

        btnMayor.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnMayor.setText("Adulto mayor");
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });

        btnDiscapacidad.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnDiscapacidad.setText("Persona con discapacidad");
        btnDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscapacidadActionPerformed(evt);
            }
        });

        btnNO.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnNO.setText("No");
        btnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNOActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lblpregunta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblpregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblpregunta.setText("¿Cumple alguna condición para atención preferencial?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblpregunta)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblpregunta)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnEmbarazada, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(btnMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmbarazada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmbarazadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmbarazadaActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL2);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnEmbarazadaActionPerformed

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL3);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnMayorActionPerformed

    private void btnDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscapacidadActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL1);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnDiscapacidadActionPerformed

    private void btnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL0);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnNOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscapacidad;
    private javax.swing.JButton btnEmbarazada;
    private javax.swing.JButton btnMayor;
    private javax.swing.JButton btnNO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpregunta;
    // End of variables declaration//GEN-END:variables
}
