/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.entity.TriagePrioridad;

/**
 *
 * @author DIEGO
 */
public class CuartoPasoCrearTurno extends javax.swing.JInternalFrame {

   private CrearTurno principal;
   
    public CuartoPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmbarazada = new javax.swing.JButton();
        btnMayor = new javax.swing.JButton();
        btnDiscapacidad = new javax.swing.JButton();
        btnNO = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblpregunta = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmbarazada.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnEmbarazada.setText("Embarazada");
        btnEmbarazada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmbarazadaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmbarazada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, 70));

        btnMayor.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnMayor.setText("Adulto mayor");
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });
        getContentPane().add(btnMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 210, 70));

        btnDiscapacidad.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnDiscapacidad.setText("Persona con discapacidad");
        btnDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscapacidadActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 300, 90));

        btnNO.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnNO.setText("No");
        btnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNOActionPerformed(evt);
            }
        });
        getContentPane().add(btnNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 210, 70));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lblpregunta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblpregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblpregunta.setText("¿Cumple alguna condición para atención preferencial?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblpregunta)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblpregunta)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmbarazadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmbarazadaActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL2);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnEmbarazadaActionPerformed

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL3);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnMayorActionPerformed

    private void btnDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscapacidadActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL1);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnDiscapacidadActionPerformed

    private void btnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL0);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnNOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscapacidad;
    private javax.swing.JButton btnEmbarazada;
    private javax.swing.JButton btnMayor;
    private javax.swing.JButton btnNO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpregunta;
    // End of variables declaration//GEN-END:variables
}
