/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.entity.TriagePrioridad;

/**
 *
 * @author DIEGO
 */
public class CuartoPasoCrearTurno extends javax.swing.JInternalFrame {

   private CrearTurno principal;
   
    public CuartoPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpregunta = new javax.swing.JLabel();
        btnEmbarazada = new javax.swing.JButton();
        btnMayor = new javax.swing.JButton();
        btnDiscapacidad = new javax.swing.JButton();
        btnNO = new javax.swing.JButton();

        lblpregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpregunta.setText("¿Cumple alguna condición para atención preferencial?");

        btnEmbarazada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEmbarazada.setText("Embarazada");
        btnEmbarazada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmbarazadaActionPerformed(evt);
            }
        });

        btnMayor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMayor.setText("Adulto mayor");
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });

        btnDiscapacidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDiscapacidad.setText("Persona con discapacidad");
        btnDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscapacidadActionPerformed(evt);
            }
        });

        btnNO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNO.setText("No");
        btnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 162, Short.MAX_VALUE)
                .addComponent(lblpregunta)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnEmbarazada, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnDiscapacidad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblpregunta)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmbarazada, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmbarazadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmbarazadaActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL2);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnEmbarazadaActionPerformed

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL3);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnMayorActionPerformed

    private void btnDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscapacidadActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL1);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnDiscapacidadActionPerformed

    private void btnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOActionPerformed
        principal.turno.setPrioridad(TriagePrioridad.LEVEL0);
        principal.pasarQuintoPaso(this);
    }//GEN-LAST:event_btnNOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscapacidad;
    private javax.swing.JButton btnEmbarazada;
    private javax.swing.JButton btnMayor;
    private javax.swing.JButton btnNO;
    private javax.swing.JLabel lblpregunta;
    // End of variables declaration//GEN-END:variables
}
