/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.entity.HistorialAtencion;
import co.edu.gestionbanco.entity.Servicio;
import co.edu.gestionbanco.entity.Turno;
import co.edu.gestionbanco.entity.Usuario;
import co.edu.gestionbanco.repository.HistorialAtencionRepository;
import co.edu.gestionbanco.repository.ServicioRepository;
import co.edu.gestionbanco.repository.TurnoRepository;
import co.edu.gestionbanco.repository.UsuarioRepository;
import java.awt.Font;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class GestionarTurno extends javax.swing.JInternalFrame {

    private Escritorio escritorio;
    private final String COLUMNAS[] = {"Turno"};
    Queue<Turno> turnoList;
    Turno turnoAtendido;
    String horaLlamado;
    int idEmpleado;

    TurnoRepository turRepository = new TurnoRepository();
    ServicioRepository serRepository = new ServicioRepository();
    UsuarioRepository usuRepository = new UsuarioRepository();
    HistorialAtencionRepository histRepository = new HistorialAtencionRepository();

    public GestionarTurno(Escritorio escritorio) {
        this.escritorio = escritorio;
        initComponents();
        empezarTrabajo();
        estilizarTabla();
    }
    
    private void estilizarTabla() {
        // Centrar texto
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblDatos.getColumnCount(); i++) {
            tblDatos.getColumnModel().getColumn(i).setCellRenderer(centrado);
        }
        
        // Aumentar la fuente
        tblDatos.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // Aumentar altura de filas
        tblDatos.setRowHeight(28);
    }

    private void setTabla(Queue<Turno> turnos) {
        List<Turno> listaTurnos = new ArrayList<>(turnos);

        Object[][] data = new Object[listaTurnos.size()][COLUMNAS.length];

        for (int i = 0; i < listaTurnos.size(); i++) {
            Turno turno = listaTurnos.get(i);
            data[i][0] = turno.getCodigo();
        }
        DefaultTableModel model = new DefaultTableModel(data, COLUMNAS) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // ninguna celda se puede editar
            }
        };
        tblDatos.setModel(model);
    }

    private void empezarTrabajo() {
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Empezar a trabajar");

        if (opcion == JOptionPane.YES_OPTION) {
            idEmpleado = escritorio.empleado.getId_empleado();
            turnoList = turRepository.getAllTurnos();
            turnoAtendido = turnoList.poll();
            setTabla(turnoList);
            cambiarTurno();
        } else {
            this.dispose();
        }
    }

    //Este metodo solo cambia lo mostrado en la pantalla, toma la hora en la que se llamo al usuario 
    //y setea la caja en la cual esta siendo atendido el turno y se cambia el estado a proceso
    //Aparte tambien manda ese turno al escritorio para que lo muestre en la tabla que esta alla 
    private void cambiarTurno() {
        horaLlamado = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));

        Servicio servicio = serRepository.getServicio(turnoAtendido.getServicio_id());
        Usuario usuario = usuRepository.getUsuarioById(turnoAtendido.getUsuario_id());

        turnoAtendido.setCaja(escritorio.empleado.getCaja());
        turnoAtendido.setEstado("Proceso");
        turRepository.actualizarEstadoTurno(turnoAtendido);
        escritorio.agregarTurno(turnoAtendido);
        lblCodigo.setText(turnoAtendido.getCodigo());
        lblNombre.setText(usuario.getNombre());
        lblServicio.setText(servicio.getNombre());
    }

    //Crea un regsitro del historial de atencion 
    private void guardarHistorialAtencion(String horaLLamado, String horaFinalizacion) {
        HistorialAtencion historial = new HistorialAtencion(idEmpleado, turnoAtendido.getId_turno(), horaLLamado, horaFinalizacion);
        histRepository.registrarHistorialAtencion(historial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        lblTituloTurno = new javax.swing.JLabel();
        sepa1 = new javax.swing.JSeparator();
        lblCodigo = new javax.swing.JLabel();
        sepa2 = new javax.swing.JSeparator();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloServicio = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Gestion de turno");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloTurno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloTurno.setText("Turno atendido");
        jPanel1.add(lblTituloTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 10, -1, -1));

        sepa1.setBackground(new java.awt.Color(0, 0, 0));
        sepa1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(sepa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 335, 10));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCodigo.setText("***");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 76, -1, -1));

        sepa2.setBackground(new java.awt.Color(0, 0, 0));
        sepa2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(sepa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 335, 10));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloNombre.setText("Nombre: ");
        jPanel1.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 136, -1, -1));

        lblTituloServicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloServicio.setText("Servicio solicitado: ");
        jPanel1.add(lblTituloServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 180, -1, -1));

        lblServicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServicio.setText("*******");
        jPanel1.add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setText("*******");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 136, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Gestor de turnos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(lblTitulo)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Se manda mensjae de confiramcion si quiere salir de trabajar, en caso de ser si se hace todo el proceso de actualizar turno 
    //y guardar el historial para luego cerrar la ventana
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Seguro desea salir?");
        if (opcion == JOptionPane.YES_OPTION) {
            String horaFinalizacion = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            turnoAtendido.setEstado("Atendido");
            guardarHistorialAtencion(horaLlamado, horaFinalizacion);
            turRepository.actualizarEstadoTurno(turnoAtendido);
            escritorio.quitarTurno(turnoAtendido);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        String horaFinalizacion = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        //Como ya se termino el turno entonces se setea el estado en Atendido
        turnoAtendido.setEstado("Atendido");
        //Luego se actualiza en la base de datos ese estado
        turRepository.actualizarEstadoTurno(turnoAtendido);
        //Se guarda el historia de atencion en la base de datos
        guardarHistorialAtencion(horaLlamado, horaFinalizacion);
        //Se llama el metodo del escritorio para quitar el turno de la tabla del escritorio
        escritorio.quitarTurno(turnoAtendido);
        //Se cambia el turno atendido con el primero de la queue y se elemina de la misma
        turnoAtendido = turnoList.poll();
        //Se llama el metodo cambiar turno para que tome el nuevo turno atendido y lo muestre
        cambiarTurno();
        //Y se actualiza la tabla
        setTabla(turnoList);
    }//GEN-LAST:event_btnTerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloServicio;
    private javax.swing.JLabel lblTituloTurno;
    private javax.swing.JSeparator sepa1;
    private javax.swing.JSeparator sepa2;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
