/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.entity.HistorialAtencion;
import co.edu.gestionbanco.entity.Servicio;
import co.edu.gestionbanco.entity.Turno;
import co.edu.gestionbanco.entity.Usuario;
import co.edu.gestionbanco.repository.HistorialAtencionRepository;
import co.edu.gestionbanco.repository.ServicioRepository;
import co.edu.gestionbanco.repository.TurnoRepository;
import co.edu.gestionbanco.repository.UsuarioRepository;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class GestionarTurno extends javax.swing.JInternalFrame {

    private Escritorio escritorio;
    private final String columnas[] = {"Turno"};
    Queue<Turno> turnoList;
    Turno turnoAtendido;
    String horaLlamado;
    int idEmpleado;

    TurnoRepository turRepository = new TurnoRepository();
    ServicioRepository serRepository = new ServicioRepository();
    UsuarioRepository usuRepository = new UsuarioRepository();
    HistorialAtencionRepository histRepository = new HistorialAtencionRepository();

    public GestionarTurno(Escritorio escritorio) {
        this.escritorio = escritorio;
        initComponents();
        empezarTrabajo();
        this.setClosable(true);
    }

    private void setTabla(Queue<Turno> turnos) {
        List<Turno> listaTurnos = new ArrayList<>(turnos);

        Object[][] data = new Object[listaTurnos.size()][columnas.length];

        for (int i = 0; i < listaTurnos.size(); i++) {
            Turno turno = listaTurnos.get(i);
            data[i][0] = turno.getCodigo();
        }

        DefaultTableModel model = new DefaultTableModel(data, columnas);
        tblDatos.setModel(model);
    }

    private void empezarTrabajo() {
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Empezar a trabajar");

        if (opcion == JOptionPane.YES_OPTION) {
            idEmpleado = escritorio.empleado.getId_empleado();
            turnoList = turRepository.getAllTurnos();
            turnoAtendido = turnoList.poll();
            setTabla(turnoList);
            cambiarTurno();
        } else {
            this.dispose();
        }
    }

    //Este metodo solo cambia lo mostrado en la pantalla, toma la hora en la que se llamo al usuario 
    //y setea la caja en la cual esta siendo atendido el turno y se cambia el estado a proceso
    //Aparte tambien manda ese turno al escritorio para que lo muestre en la tabla que esta alla 
    private void cambiarTurno() {
        horaLlamado = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));

        Servicio servicio = serRepository.getServicio(turnoAtendido.getServicio_id());
        Usuario usuario = usuRepository.getUsuario(turnoAtendido.getUsuario_id());

        turnoAtendido.setCaja(escritorio.empleado.getCaja());
        turnoAtendido.setEstado("Proceso");
        turRepository.actualizarEstadoTurno(turnoAtendido);
        escritorio.agregarTurno(turnoAtendido);

        lblCodigo.setText(turnoAtendido.getCodigo());
        lblNombre.setText(usuario.getNombre());
        lblServicio.setText(servicio.getNombre());
    }

    //Crea un regsitro del historial de atencion 
    private void guardarHistorialAtencion(String horaLLamado, String horaFinalizacion) {
        HistorialAtencion historial = new HistorialAtencion(idEmpleado, turnoAtendido.getId_turno(), horaLLamado, horaFinalizacion);
        histRepository.registrarHistorialAtencion(historial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTituloTurno = new javax.swing.JLabel();
        sepa1 = new javax.swing.JSeparator();
        lblCodigo = new javax.swing.JLabel();
        sepa2 = new javax.swing.JSeparator();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloServicio = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Gestion de turno");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Gestor de turnos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloTurno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloTurno.setText("Turno atendido");

        sepa1.setBackground(new java.awt.Color(0, 0, 0));
        sepa1.setForeground(new java.awt.Color(0, 0, 0));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCodigo.setText("***");

        sepa2.setBackground(new java.awt.Color(0, 0, 0));
        sepa2.setForeground(new java.awt.Color(0, 0, 0));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloNombre.setText("Nombre: ");

        lblTituloServicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloServicio.setText("Servicio solicitado: ");

        lblServicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServicio.setText("*******");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setText("*******");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepa1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sepa2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTituloNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblTituloServicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblServicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lblCodigo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblTituloTurno)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTituloTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepa1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepa2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloNombre)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloServicio)
                .addGap(18, 18, 18)
                .addComponent(lblServicio)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Se manda mensjae de confiramcion si quiere salir de trabajar, en caso de ser si se hace todo el proceso de actualizar turno 
    //y guardar el historial para luego cerrar la ventana
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Seguro desea salir?");
        if (opcion == JOptionPane.YES_OPTION) {
            String horaFinalizacion = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            turnoAtendido.setEstado("Atendido");
            guardarHistorialAtencion(horaLlamado, horaFinalizacion);
            turRepository.actualizarEstadoTurno(turnoAtendido);
            escritorio.quitarTurno(turnoAtendido);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        String horaFinalizacion = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        //Como ya se termino el turno entonces se setea el estado en Atendido
        turnoAtendido.setEstado("Atendido");
        //Luego se actualiza en la base de datos ese estado
        turRepository.actualizarEstadoTurno(turnoAtendido);
        //Se guarda el historia de atencion en la base de datos
        guardarHistorialAtencion(horaLlamado, horaFinalizacion);
        //Se llama el metodo del escritorio para quitar el turno de la tabla del escritorio
        escritorio.quitarTurno(turnoAtendido);
        //Se cambia el turno atendido con el primero de la queue y se elemina de la misma
        turnoAtendido = turnoList.poll();
        //Se llama el metodo cambiar turno para que tome el nuevo turno atendido y lo muestre
        cambiarTurno();
        //Y se actualiza la tabla
        setTabla(turnoList);
    }//GEN-LAST:event_btnTerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloServicio;
    private javax.swing.JLabel lblTituloTurno;
    private javax.swing.JSeparator sepa1;
    private javax.swing.JSeparator sepa2;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
