/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

/**
 *
 * @author DIEGO
 */
public class PrimerPasoCrearTurno extends javax.swing.JInternalFrame {

    private CrearTurno principal;
    
    
    public PrimerPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPan1No = new javax.swing.JButton();
        btnPan1Si = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPan1pregunta = new javax.swing.JLabel();

        btnPan1No.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnPan1No.setText("No, aún no soy cliente");
        btnPan1No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan1NoActionPerformed(evt);
            }
        });

        btnPan1Si.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnPan1Si.setText("Sí, soy cliente BBVA");
        btnPan1Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan1SiActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lblPan1pregunta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPan1pregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblPan1pregunta.setText("¿Ya eres cliente del BBVA?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPan1pregunta)
                .addGap(302, 302, 302))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPan1pregunta)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnPan1Si, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnPan1No, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPan1Si, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnPan1No, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPan1NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan1NoActionPerformed
        principal.esCliente = false;
        principal.pasarSegundoPaso();
    }//GEN-LAST:event_btnPan1NoActionPerformed

    private void btnPan1SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan1SiActionPerformed
        principal.esCliente = true;
        principal.pasarSegundoPaso();
    }//GEN-LAST:event_btnPan1SiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPan1No;
    private javax.swing.JButton btnPan1Si;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPan1pregunta;
    // End of variables declaration//GEN-END:variables
}
