/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

/**
 *
 * @author DIEGO
 */
public class PrimerPasoCrearTurno extends javax.swing.JInternalFrame {

    private CrearTurno principal;
    
    
    public PrimerPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPan1pregunta = new javax.swing.JLabel();
        btnPan1No = new javax.swing.JButton();
        btnPan1Si = new javax.swing.JButton();

        lblPan1pregunta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPan1pregunta.setText("¿Ya eres cliente del BBVA?");

        btnPan1No.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan1No.setText("No, aún no soy cliente");
        btnPan1No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan1NoActionPerformed(evt);
            }
        });

        btnPan1Si.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPan1Si.setText("Sí, soy cliente BBVA");
        btnPan1Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPan1SiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPan1Si, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(btnPan1No, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPan1pregunta)
                        .addGap(296, 296, 296))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblPan1pregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPan1Si, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPan1No, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPan1NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan1NoActionPerformed
        principal.esCliente = false;
        principal.pasarSegundoPaso();
    }//GEN-LAST:event_btnPan1NoActionPerformed

    private void btnPan1SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPan1SiActionPerformed
        principal.esCliente = true;
        principal.pasarSegundoPaso();
    }//GEN-LAST:event_btnPan1SiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPan1No;
    private javax.swing.JButton btnPan1Si;
    private javax.swing.JLabel lblPan1pregunta;
    // End of variables declaration//GEN-END:variables
}
