/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author DIEGO
 */
public class QuintoPasoCrearTurno extends javax.swing.JInternalFrame {

    private CrearTurno principal;

    public QuintoPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
        crearTurno();

    }

    private void crearTurno() {
        if(principal.crearTurno()) {
            mostrarTurno();
        };
    }

    private void mostrarTurno() {
        lblCodigo.setText(principal.turno.getCodigo());
        lblFechaHora.setText(principal.turno.getFecha() + " " + principal.turno.getHora());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        pnaPan5ContenedorTicket = new javax.swing.JPanel();
        lblTituloTurno = new javax.swing.JLabel();
        sepa1 = new javax.swing.JSeparator();
        lblCodigo = new javax.swing.JLabel();
        sepa2 = new javax.swing.JSeparator();
        lblFechaHora = new javax.swing.JLabel();
        lblTituloEspere = new javax.swing.JLabel();
        lblTituloSinTicket = new javax.swing.JLabel();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Turno generado");

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPregunta.setText("¡Gracias, por confiar en nosotros!");

        pnaPan5ContenedorTicket.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloTurno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloTurno.setText("Tu turno:");

        sepa1.setBackground(new java.awt.Color(0, 0, 0));
        sepa1.setForeground(new java.awt.Color(0, 0, 0));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCodigo.setText("***");

        sepa2.setBackground(new java.awt.Color(0, 0, 0));
        sepa2.setForeground(new java.awt.Color(0, 0, 0));

        lblFechaHora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaHora.setText("********** ********");

        lblTituloEspere.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloEspere.setText("Espere a ser llamado");

        lblTituloSinTicket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloSinTicket.setText("Sin el ticket no puede ser atendido");

        javax.swing.GroupLayout pnaPan5ContenedorTicketLayout = new javax.swing.GroupLayout(pnaPan5ContenedorTicket);
        pnaPan5ContenedorTicket.setLayout(pnaPan5ContenedorTicketLayout);
        pnaPan5ContenedorTicketLayout.setHorizontalGroup(
            pnaPan5ContenedorTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepa1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sepa2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnaPan5ContenedorTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addComponent(lblTituloTurno)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addComponent(lblTituloSinTicket)
                        .addGap(18, 18, 18))))
            .addGroup(pnaPan5ContenedorTicketLayout.createSequentialGroup()
                .addGroup(pnaPan5ContenedorTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblTituloEspere))
                    .addGroup(pnaPan5ContenedorTicketLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblCodigo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnaPan5ContenedorTicketLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblFechaHora)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnaPan5ContenedorTicketLayout.setVerticalGroup(
            pnaPan5ContenedorTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaPan5ContenedorTicketLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTituloTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepa1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepa2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloEspere)
                .addGap(18, 18, 18)
                .addComponent(lblTituloSinTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lblFechaHora)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblPregunta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblTitulo))
                    .addComponent(pnaPan5ContenedorTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnaPan5ContenedorTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloEspere;
    private javax.swing.JLabel lblTituloSinTicket;
    private javax.swing.JLabel lblTituloTurno;
    private javax.swing.JPanel pnaPan5ContenedorTicket;
    private javax.swing.JSeparator sepa1;
    private javax.swing.JSeparator sepa2;
    // End of variables declaration//GEN-END:variables
}
