/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author DIEGO
 */
public class QuintoPasoCrearTurno extends javax.swing.JInternalFrame {

    private CrearTurno principal;

    public QuintoPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
        crearTurno();

    }

    private void crearTurno() {
        if(principal.crearTurno()) {
            mostrarTurno();
        };
    }

    private void mostrarTurno() {
        lblCodigo.setText(principal.turno.getCodigo());
        lblFechaHora.setText(principal.turno.getFecha() + " " + principal.turno.getHora());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnaPan5ContenedorTicket = new javax.swing.JPanel();
        lblTituloTurno = new javax.swing.JLabel();
        sepa1 = new javax.swing.JSeparator();
        lblCodigo = new javax.swing.JLabel();
        sepa2 = new javax.swing.JSeparator();
        lblFechaHora = new javax.swing.JLabel();
        lblTituloEspere = new javax.swing.JLabel();
        lblTituloSinTicket = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        pnaPan5ContenedorTicket.setBackground(new java.awt.Color(255, 255, 255));
        pnaPan5ContenedorTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloTurno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloTurno.setText("Tu turno:");
        pnaPan5ContenedorTicket.add(lblTituloTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        sepa1.setBackground(new java.awt.Color(0, 0, 0));
        sepa1.setForeground(new java.awt.Color(0, 0, 0));
        pnaPan5ContenedorTicket.add(sepa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 317, 10));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCodigo.setText("***");
        pnaPan5ContenedorTicket.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 76, -1, -1));

        sepa2.setBackground(new java.awt.Color(0, 0, 0));
        sepa2.setForeground(new java.awt.Color(0, 0, 0));
        pnaPan5ContenedorTicket.add(sepa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 317, 10));

        lblFechaHora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaHora.setText("********** ********");
        pnaPan5ContenedorTicket.add(lblFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 254, -1, -1));

        lblTituloEspere.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloEspere.setText("Espere a ser llamado");
        pnaPan5ContenedorTicket.add(lblTituloEspere, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 142, -1, -1));

        lblTituloSinTicket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloSinTicket.setText("Sin el ticket no puede ser atendido");
        pnaPan5ContenedorTicket.add(lblTituloSinTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, -1, -1));

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPregunta.setText("¡Gracias, por confiar en nosotros!");

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Turno generado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnaPan5ContenedorTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPregunta))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPregunta)
                .addGap(18, 18, 18)
                .addComponent(pnaPan5ContenedorTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloEspere;
    private javax.swing.JLabel lblTituloSinTicket;
    private javax.swing.JLabel lblTituloTurno;
    private javax.swing.JPanel pnaPan5ContenedorTicket;
    private javax.swing.JSeparator sepa1;
    private javax.swing.JSeparator sepa2;
    // End of variables declaration//GEN-END:variables
}
