/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.repository.UsuarioRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO
 */
public class SegundoPasoCrerTurno extends javax.swing.JInternalFrame {

    private CrearTurno principal;

    public SegundoPasoCrerTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTeclado6 = new javax.swing.JButton();
        btnTeclado9 = new javax.swing.JButton();
        txtDocumento = new javax.swing.JTextField();
        btnTeclado8 = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnTeclado7 = new javax.swing.JButton();
        btnTeclado5 = new javax.swing.JButton();
        btnTeclado0 = new javax.swing.JButton();
        btnTeclado3 = new javax.swing.JButton();
        btnTeclado2 = new javax.swing.JButton();
        btnTeclado1 = new javax.swing.JButton();
        btnTeclado4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblpregunta = new javax.swing.JLabel();

        btnTeclado6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado6.setText("6");
        btnTeclado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado6ActionPerformed(evt);
            }
        });

        btnTeclado9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado9.setText("9");
        btnTeclado9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado9ActionPerformed(evt);
            }
        });

        txtDocumento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        btnTeclado8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado8.setText("8");
        btnTeclado8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado8ActionPerformed(evt);
            }
        });

        btnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnTeclado7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado7.setText("7");
        btnTeclado7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado7ActionPerformed(evt);
            }
        });

        btnTeclado5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado5.setText("5");
        btnTeclado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado5ActionPerformed(evt);
            }
        });

        btnTeclado0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado0.setText("0");
        btnTeclado0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado0ActionPerformed(evt);
            }
        });

        btnTeclado3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado3.setText("3");
        btnTeclado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado3ActionPerformed(evt);
            }
        });

        btnTeclado2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado2.setText("2");
        btnTeclado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado2ActionPerformed(evt);
            }
        });

        btnTeclado1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado1.setText("1");
        btnTeclado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado1ActionPerformed(evt);
            }
        });

        btnTeclado4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeclado4.setText("4");
        btnTeclado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado4ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lblpregunta.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblpregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblpregunta.setText("Por favor, ingresa tu número de documento para continuar con la solicitud.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpregunta)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblpregunta)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTeclado9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnContinuar)
                        .addGap(204, 204, 204)
                        .addComponent(btnTeclado3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTeclado8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTeclado7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTeclado0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTeclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTeclado9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTeclado5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTeclado3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTeclado0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeclado9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado9ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado9.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado9ActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed

    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void btnTeclado8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado8ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado8.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado8ActionPerformed

    private void btnTeclado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado5ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado5.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado5ActionPerformed

    private void btnTeclado0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado0ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado0.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado0ActionPerformed

    private void btnTeclado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado3ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado3.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado3ActionPerformed

    private void btnTeclado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado2ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado2.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado2ActionPerformed

    private void btnTeclado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado4ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado4.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado4ActionPerformed

    private void btnTeclado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado1ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado1.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado1ActionPerformed

    private void btnTeclado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado6ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado6.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado6ActionPerformed

    private void btnTeclado7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado7ActionPerformed
        String documento = txtDocumento.getText();
        documento += btnTeclado7.getText();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_btnTeclado7ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        UsuarioRepository repository = new UsuarioRepository();
        
        int documento = Integer.parseInt(txtDocumento.getText());
        principal.usuario = repository.getUsuario(documento);
        int idUsuario = principal.usuario.getId_usuario();
        
        //Si es cliente y el nombre es null y el idUsuario es diferente a cero es porque es invitado pero dijo que era cliente
        if(principal.esCliente && principal.usuario.getNombre() == null && idUsuario != 0){
            principal.esCliente = false;
        }
        
        if(!principal.esCliente && idUsuario == 0 ){
            repository.registrarInvitado(documento);
            principal.usuario = repository.getUsuario(documento);
            idUsuario = principal.usuario.getId_usuario();
        }
        
        //Si no encontro un usuario deja escribir de nuevo, solo se activa si es cliente ya que si no lo es las lineas anteriores de codigo lo abran registrado
        if(idUsuario == 0){
            JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            txtDocumento.setText("");
        }else{
            principal.pasarTercerPaso(this);
        }
        //Aqui lo que se hace es que si no es cliente pero dice que lo es y al escribir el documetno se encuentra un regsitro con ese documento pero sin la otra info
        //es porque en realidad es invitado que ya ha estado
        //Entonces se le cambia que no es un cliente, por ende se activa el segundo condicional si es que no es cleinte y no se encontro un registro
        //con el mismo documento para que el sistema lo registre, si se encotro el resgitro entonces no vuelve a registrarlo
        //y ya por ultimo si es cleinte y no se encontro la cedula deja escribirlo de nuevo
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnTeclado0;
    private javax.swing.JButton btnTeclado1;
    private javax.swing.JButton btnTeclado2;
    private javax.swing.JButton btnTeclado3;
    private javax.swing.JButton btnTeclado4;
    private javax.swing.JButton btnTeclado5;
    private javax.swing.JButton btnTeclado6;
    private javax.swing.JButton btnTeclado7;
    private javax.swing.JButton btnTeclado8;
    private javax.swing.JButton btnTeclado9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpregunta;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
