/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.entity.Servicio;
import co.edu.gestionbanco.repository.ServicioRepository;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class TercerPasoCrearTurno extends javax.swing.JInternalFrame {

    private final String COLUMNAS[] = {"Servicio", "Descripcion"};

    //Para tener la informacion de todos los servicios
    private List<Servicio> serviciosLista;

    private CrearTurno principal;

    public TercerPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
        colocarNombre();
        inicializarTabla(traerDatos());
    }
    
    private void colocarNombre(){
        if(principal.esCliente){
            String text = lblPan3bienvenida.getText();
            text +=  ", "+principal.usuario.getNombre();
            lblPan3bienvenida.setText(text);
        }
    }

    private void inicializarTabla(List<Servicio> servicios) {
        this.serviciosLista = servicios;
        Object[][] data = new Object[servicios.size()][COLUMNAS.length];
        
        //Filtro para servicios de clientes y de no clientes (Tablas de verdad importantes)
        servicios = servicios.stream().filter(s -> s.getExclusivoCliente() == 0 || principal.esCliente).collect(Collectors.toList());        
                
        for (int i = 0; i < servicios.size(); i++) {

            Servicio servicio = servicios.get(i);
                data[i][0] = servicio.getNombre();
                data[i][1] = servicio.getDescripcion(); // ejemplo

        }

        DefaultTableModel model = new DefaultTableModel(data, COLUMNAS);
        tblDatos.setModel(model);
    }

    private List<Servicio> traerDatos() {
        ServicioRepository serRepository = new ServicioRepository();
        List<Servicio> serList = serRepository.getAllServicios();

        return serList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPan3pregunta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblPan3bienvenida = new javax.swing.JLabel();

        lblPan3pregunta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPan3pregunta.setText("¿Que servicio desea realizar?");

        tblDatos.setAutoCreateRowSorter(true);
        tblDatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Servicio", "Descipcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDatos);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 50));

        lblPan3bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPan3bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblPan3bienvenida.setText("Bienvenido ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(lblPan3bienvenida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPan3bienvenida)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPan3pregunta)
                        .addGap(325, 325, 325))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPan3pregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        int fila = tblDatos.getSelectedRow();
        Servicio servicio = serviciosLista.get(fila);
        principal.servicio = servicio;
        principal.pasarCuartoPaso(this);
    }//GEN-LAST:event_tblDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPan3bienvenida;
    private javax.swing.JLabel lblPan3pregunta;
    private javax.swing.JLabel lblpregunta;
    private javax.swing.JLabel lblpregunta1;
    private javax.swing.JLabel lblpregunta2;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
