/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.gestionbanco.ui;

import co.edu.gestionbanco.entity.Servicio;
import co.edu.gestionbanco.repository.ServicioRepository;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class TercerPasoCrearTurno extends javax.swing.JInternalFrame {

    private final String columnas[] = {"Servicio", "Descripcion"};

    //Para tener la informacion de todos los servicios
    private List<Servicio> serviciosLista;

    private CrearTurno principal;

    public TercerPasoCrearTurno(CrearTurno principal) {
        this.principal = principal;
        initComponents();
        colocarNombre();
        inicializarTabla(traerDatos());
    }
    
    public void colocarNombre(){
        if(principal.esCliente){
            String text = lblPan3bienvenida.getText();
            text +=  ", "+principal.usuario.getNombre();
            lblPan3bienvenida.setText(text);
        }
    }

    public void inicializarTabla(List<Servicio> servicios) {
        this.serviciosLista = servicios;
        Object[][] data = new Object[servicios.size()][columnas.length];
        
        //Filtro para servicios de clientes y de no clientes (Tablas de verdad importantes)
        servicios = servicios.stream().filter(s -> s.getExclusivoCliente() == 0 || principal.esCliente).collect(Collectors.toList());        
                
        for (int i = 0; i < servicios.size(); i++) {

            Servicio servicio = servicios.get(i);
                data[i][0] = servicio.getNombre();
                data[i][1] = servicio.getDescripcion(); // ejemplo

        }

        DefaultTableModel model = new DefaultTableModel(data, columnas);
        tblDatos.setModel(model);
    }

    public List<Servicio> traerDatos() {
        ServicioRepository serRepository = new ServicioRepository();
        List<Servicio> turnoList = serRepository.getAllServicios();

        return turnoList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPan3bienvenida = new javax.swing.JLabel();
        lblPan3pregunta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        lblPan3bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan3bienvenida.setText("Bienvenido ");

        lblPan3pregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPan3pregunta.setText("¿Que servicio desea realizar?");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Servicio", "Descipcion"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPan3bienvenida)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(lblPan3pregunta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblPan3bienvenida)
                .addGap(18, 18, 18)
                .addComponent(lblPan3pregunta)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        int fila = tblDatos.getSelectedRow();
        Servicio servicio = serviciosLista.get(fila);
        principal.servicio = servicio;
        principal.pasarCuartoPaso(this);
    }//GEN-LAST:event_tblDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPan3bienvenida;
    private javax.swing.JLabel lblPan3pregunta;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
